import dummyImg from "../images/dummy.png";
import dummyVideoImg from "../images/video.svg"

export const ContentManagementData = [
    {
        id: 1,
        eeSectorCode: "EE_SSC_486",
        sectorType: "Government Sector",
        sectorSkillName: "SCGJ",
        spocName: "Richa Mehta",
        mobile: "0123456789",
        email: "richamehta@gmail.com",
        password: "ZNKEIGAM",
        coordinatorEmail: "richamehta@gmail.com",
        logo: dummyImg,
        status: "Active for Sector",
    },
    {
        id: 2,
        eeSectorCode: "FE_SSC_486",
        sectorType: "Government Sector",
        sectorSkillName: "HCGJ",
        spocName: "Richa Mehta",
        mobile: "0123456789",
        email: "richamehta@gmail.com",
        password: "ZNKEIGAM",
        coordinatorEmail: "richamehta@gmail.com",
        logo: dummyImg,
        status: "Active for Sector",
    },
    {
        id: 3,
        eeSectorCode: "FE_SSC_490",
        sectorType: "Government Sector",
        sectorSkillName: "HCGJ",
        spocName: "Richa Mehta",
        mobile: "0123456789",
        email: "richamehta@gmail.com",
        password: "ZNKEIGAM",
        coordinatorEmail: "richamehta@gmail.com",
        logo: dummyImg,
        status: "Active for Sector",
    },
    {
        id: 4,
        eeSectorCode: "FE_SSC_492",
        sectorType: "Government Sector",
        sectorSkillName: "HCGJ",
        spocName: "Richa Mehta",
        mobile: "0123456789",
        email: "richamehta@gmail.com",
        password: "ZNKEIGAM",
        coordinatorEmail: "richamehta@gmail.com",
        logo: dummyImg,
        status: "Active for Sector",
    },
    {
        id: 5,
        eeSectorCode: "FE_SSC_494",
        sectorType: "Government Sector",
        sectorSkillName: "HCGJ",
        spocName: "Richa Mehta",
        mobile: "0123456789",
        email: "richamehta@gmail.com",
        password: "ZNKEIGAM",
        coordinatorEmail: "richamehta@gmail.com",
        logo: dummyImg,
        status: "Active for Sector",
    },
    {
        id: 6,
        eeSectorCode: "FE_SSC_496",
        sectorType: "Government Sector",
        sectorSkillName: "HCGJ",
        spocName: "Richa Mehta",
        mobile: "0123456789",
        email: "richamehta@gmail.com",
        password: "ZNKEIGAM",
        coordinatorEmail: "richamehta@gmail.com",
        logo: dummyImg,
        status: "Active for Sector",
    },
    {
        id: 7,
        eeSectorCode: "FE_SSC_498",
        sectorType: "Government Sector",
        sectorSkillName: "HCGJ",
        spocName: "Richa Mehta",
        mobile: "0123456789",
        email: "richamehta@gmail.com",
        password: "ZNKEIGAM",
        coordinatorEmail: "richamehta@gmail.com",
        logo: dummyImg,
        status: "Active for Sector",
    },
    {
        id: 8,
        eeSectorCode: "FE_SSC_478",
        sectorType: "Government Sector",
        sectorSkillName: "HCGJ",
        spocName: "Richa Mehta",
        mobile: "0123456789",
        email: "richamehta@gmail.com",
        password: "ZNKEIGAM",
        coordinatorEmail: "richamehta@gmail.com",
        logo: dummyImg,
        status: "Active for Sector",
    },
    {
        id: 9,
        eeSectorCode: "FE_SSC_476",
        sectorType: "Government Sector",
        sectorSkillName: "HCGJ",
        spocName: "Richa Mehta",
        mobile: "0123456789",
        email: "richamehta@gmail.com",
        password: "ZNKEIGAM",
        coordinatorEmail: "richamehta@gmail.com",
        logo: dummyImg,
        status: "Active for Sector",
    },
    {
        id: 10,
        eeSectorCode: "FE_SSC_474",
        sectorType: "Government Sector",
        sectorSkillName: "HCGJ",
        spocName: "Richa Mehta",
        mobile: "0123456789",
        email: "richamehta@gmail.com",
        password: "ZNKEIGAM",
        coordinatorEmail: "richamehta@gmail.com",
        logo: dummyImg,
        status: "Active for Sector",
    },
    {
        id: 11,
        eeSectorCode: "FE_SSC_472",
        sectorType: "Government Sector",
        sectorSkillName: "HCGJ",
        spocName: "Richa Mehta",
        mobile: "0123456789",
        email: "richamehta@gmail.com",
        password: "ZNKEIGAM",
        coordinatorEmail: "richamehta@gmail.com",
        logo: dummyImg,
        status: "Active for Sector",
    },
    {
        id: 12,
        eeSectorCode: "FE_SSC_470",
        sectorType: "Government Sector",
        sectorSkillName: "HCGJ",
        spocName: "Richa Mehta",
        mobile: "0123456789",
        email: "richamehta@gmail.com",
        password: "ZNKEIGAM",
        coordinatorEmail: "richamehta@gmail.com",
        logo: dummyImg,
        status: "Active for Sector",
    }
]

export const ManageQuestionBankData = [
    {
        id: 1,
        eeSectorCode: "EE_SSC_486",
        QuestionBankCode: "QB_1873",
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        QuestionBankType: "Theory",
        SectorName: "SCGJ",
        JobRoleName: "Solar PV Installer-Suryamitra",
        PracticalType: "",
        TotalQuestion: "50",
    },
    {
        id: 2,
        eeSectorCode: "FE_SSC_486",
        QuestionBankCode: "QB_1873",
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        QuestionBankType: "Theory",
        SectorName: "SCGJ",
        JobRoleName: "Solar PV Installer-Suryamitra",
        PracticalType: "",
        TotalQuestion: "50",
    },
    {
        id: 3,
        eeSectorCode: "FE_SSC_490",
        QuestionBankCode: "QB_1873",
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        QuestionBankType: "Theory",
        SectorName: "SCGJ",
        JobRoleName: "Solar PV Installer-Suryamitra",
        PracticalType: "",
        TotalQuestion: "50",
    },
    {
        id: 4,
        eeSectorCode: "FE_SSC_492",
        QuestionBankCode: "QB_1873",
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        QuestionBankType: "Theory",
        SectorName: "SCGJ",
        JobRoleName: "Solar PV Installer-Suryamitra",
        PracticalType: "",
        TotalQuestion: "50",
    },
    {
        id: 5,
        eeSectorCode: "FE_SSC_494",
        QuestionBankCode: "QB_1873",
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        QuestionBankType: "Theory",
        SectorName: "SCGJ",
        JobRoleName: "Solar PV Installer-Suryamitra",
        PracticalType: "",
        TotalQuestion: "50",
    },
    {
        id: 6,
        eeSectorCode: "FE_SSC_496",
        QuestionBankCode: "QB_1873",
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        QuestionBankType: "Theory",
        SectorName: "SCGJ",
        JobRoleName: "Solar PV Installer-Suryamitra",
        PracticalType: "",
        TotalQuestion: "50",
    },
    {
        id: 7,
        eeSectorCode: "FE_SSC_498",
        QuestionBankCode: "QB_1873",
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        QuestionBankType: "Theory",
        SectorName: "SCGJ",
        JobRoleName: "Solar PV Installer-Suryamitra",
        PracticalType: "",
        TotalQuestion: "50",
    },
    {
        id: 8,
        eeSectorCode: "FE_SSC_478",
        QuestionBankCode: "QB_1873",
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        QuestionBankType: "Theory",
        SectorName: "SCGJ",
        JobRoleName: "Solar PV Installer-Suryamitra",
        PracticalType: "",
        TotalQuestion: "50",
    },
    {
        id: 9,
        eeSectorCode: "FE_SSC_476",
        QuestionBankCode: "QB_1873",
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        QuestionBankType: "Theory",
        SectorName: "SCGJ",
        JobRoleName: "Solar PV Installer-Suryamitra",
        PracticalType: "",
        TotalQuestion: "50",
    },
    {
        id: 10,
        eeSectorCode: "FE_SSC_474",
        QuestionBankCode: "QB_1873",
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        QuestionBankType: "Theory",
        SectorName: "SCGJ",
        JobRoleName: "Solar PV Installer-Suryamitra",
        PracticalType: "",
        TotalQuestion: "50",
    },
    {
        id: 11,
        eeSectorCode: "FE_SSC_472",
        QuestionBankCode: "QB_1873",
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        QuestionBankType: "Theory",
        SectorName: "SCGJ",
        JobRoleName: "Solar PV Installer-Suryamitra",
        PracticalType: "",
        TotalQuestion: "50",
    },
    {
        id: 12,
        eeSectorCode: "FE_SSC_470",
        QuestionBankCode: "QB_1873",
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        QuestionBankType: "Theory",
        SectorName: "SCGJ",
        JobRoleName: "Solar PV Installer-Suryamitra",
        PracticalType: "",
        TotalQuestion: "50",
    }
]

export const ManageChildUserData = [
    {
        id: 1,
        QuestionID: 4486,
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        nos: "Site Survey for Installation of Solar PV System",
        Question:
            "Which of the following is a main disadvantage of a solar PV system",
        Option1: "1. Capital cost",
        Option2: "2. Operation Cost",
        Option3: "3. Maintaince cost",
        Option4: "4. Life cycle cost",
        QuestionMarks: "1",
        Difficulty: "2",
    },
    {
        id: 2,
        QuestionID: 4486,
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        nos: "Site Survey for Installation of Solar PV System",
        Question:
            "Which of the following is a main disadvantage of a solar PV system",
        Option1: "1. Capital cost",
        Option2: "2. Operation Cost",
        Option3: "3. Maintaince cost",
        Option4: "4. Life cycle cost",
        QuestionMarks: "1",
        Difficulty: "2",
    },
    {
        id: 3,
        QuestionID: 4486,
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        nos: "Site Survey for Installation of Solar PV System",
        Question:
            "Which of the following is a main disadvantage of a solar PV system",
        Option1: "1. Capital cost",
        Option2: "2. Operation Cost",
        Option3: "3. Maintaince cost",
        Option4: "4. Life cycle cost",
        QuestionMarks: "1",
        Difficulty: "2",
    },
    {
        id: 4,
        QuestionID: 4486,
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        nos: "Site Survey for Installation of Solar PV System",
        Question:
            "Which of the following is a main disadvantage of a solar PV system",
        Option1: "1. Capital cost",
        Option2: "2. Operation Cost",
        Option3: "3. Maintaince cost",
        Option4: "4. Life cycle cost",
        QuestionMarks: "1",
        Difficulty: "2",
    },
    {
        id: 5,
        QuestionID: 4486,
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        nos: "Site Survey for Installation of Solar PV System",
        Question:
            "Which of the following is a main disadvantage of a solar PV system",
        Option1: "1. Capital cost",
        Option2: "2. Operation Cost",
        Option3: "3. Maintaince cost",
        Option4: "4. Life cycle cost",
        QuestionMarks: "1",
        Difficulty: "2",
    },
    {
        id: 6,
        QuestionID: 4486,
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        nos: "Site Survey for Installation of Solar PV System",
        Question:
            "Which of the following is a main disadvantage of a solar PV system",
        Option1: "1. Capital cost",
        Option2: "2. Operation Cost",
        Option3: "3. Maintaince cost",
        Option4: "4. Life cycle cost",
        QuestionMarks: "1",
        Difficulty: "2",
    },
    {
        id: 7,
        QuestionID: 4486,
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        nos: "Site Survey for Installation of Solar PV System",
        Question:
            "Which of the following is a main disadvantage of a solar PV system",
        Option1: "1. Capital cost",
        Option2: "2. Operation Cost",
        Option3: "3. Maintaince cost",
        Option4: "4. Life cycle cost",
        QuestionMarks: "1",
        Difficulty: "2",
    },
    {
        id: 8,
        QuestionID: 4486,
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        nos: "Site Survey for Installation of Solar PV System",
        Question:
            "Which of the following is a main disadvantage of a solar PV system",
        Option1: "1. Capital cost",
        Option2: "2. Operation Cost",
        Option3: "3. Maintaince cost",
        Option4: "4. Life cycle cost",
        QuestionMarks: "1",
        Difficulty: "2",
    },
    {
        id: 9,
        QuestionID: 4486,
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        nos: "Site Survey for Installation of Solar PV System",
        Question:
            "Which of the following is a main disadvantage of a solar PV system",
        Option1: "1. Capital cost",
        Option2: "2. Operation Cost",
        Option3: "3. Maintaince cost",
        Option4: "4. Life cycle cost",
        QuestionMarks: "1",
        Difficulty: "2",
    },
    {
        id: 10,
        QuestionID: 4486,
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        nos: "Site Survey for Installation of Solar PV System",
        Question:
            "Which of the following is a main disadvantage of a solar PV system",
        Option1: "1. Capital cost",
        Option2: "2. Operation Cost",
        Option3: "3. Maintaince cost",
        Option4: "4. Life cycle cost",
        QuestionMarks: "1",
        Difficulty: "2",
    },
    {
        id: 11,
        QuestionID: 4486,
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        nos: "Site Survey for Installation of Solar PV System",
        Question:
            "Which of the following is a main disadvantage of a solar PV system",
        Option1: "1. Capital cost",
        Option2: "2. Operation Cost",
        Option3: "3. Maintaince cost",
        Option4: "4. Life cycle cost",
        QuestionMarks: "1",
        Difficulty: "2",
    },
    {
        id: 12,
        QuestionID: 4486,
        QuestionBankName: "Solar PV Installer ( Suryamitra)",
        nos: "Site Survey for Installation of Solar PV System",
        Question:
            "Which of the following is a main disadvantage of a solar PV system",
        Option1: "1. Capital cost",
        Option2: "2. Operation Cost",
        Option3: "3. Maintaince cost",
        Option4: "4. Life cycle cost",
        QuestionMarks: "1",
        Difficulty: "2",
    }
]

export const AssessmentData = [
    {
        id: 1,
        BatchID: "EE_SSC_486",
        BatchName: "Government Sector",
        TPName: "SCGJ",
        TCenter: "Richa Mehta",
        ToAssessmentDate: "0123456789",
        StartTime: "11:00 AM",
        EndTime: "02:00 PM",
        TotalCandidate: "1000",
        EnablePhoto: dummyImg,
        EnableVideo: dummyVideoImg,
    },
    {
        id: 2,
        BatchID: "EE_SSC_486",
        BatchName: "Government Sector",
        TPName: "SCGJ",
        TCenter: "Richa Mehta",
        ToAssessmentDate: "0123456789",
        StartTime: "11:00 AM",
        EndTime: "02:00 PM",
        TotalCandidate: "1000",
        EnablePhoto: dummyImg,
        EnableVideo: dummyVideoImg,
    },
    {
        id: 3,
        BatchID: "EE_SSC_486",
        BatchName: "Government Sector",
        TPName: "SCGJ",
        TCenter: "Richa Mehta",
        ToAssessmentDate: "0123456789",
        StartTime: "11:00 AM",
        EndTime: "02:00 PM",
        TotalCandidate: "1000",
        EnablePhoto: dummyImg,
        EnableVideo: dummyVideoImg,
    },
    {
        id: 4,
        BatchID: "EE_SSC_486",
        BatchName: "Government Sector",
        TPName: "SCGJ",
        TCenter: "Richa Mehta",
        ToAssessmentDate: "0123456789",
        StartTime: "11:00 AM",
        EndTime: "02:00 PM",
        TotalCandidate: "1000",
        EnablePhoto: dummyImg,
        EnableVideo: dummyVideoImg,
    },
    {
        id: 5,
        BatchID: "EE_SSC_486",
        BatchName: "Government Sector",
        TPName: "SCGJ",
        TCenter: "Richa Mehta",
        ToAssessmentDate: "0123456789",
        StartTime: "11:00 AM",
        EndTime: "02:00 PM",
        TotalCandidate: "1000",
        EnablePhoto: dummyImg,
        EnableVideo: dummyVideoImg,
    },
    {
        id: 6,
        BatchID: "EE_SSC_486",
        BatchName: "Government Sector",
        TPName: "SCGJ",
        TCenter: "Richa Mehta",
        ToAssessmentDate: "0123456789",
        StartTime: "11:00 AM",
        EndTime: "02:00 PM",
        TotalCandidate: "1000",
        EnablePhoto: dummyImg,
        EnableVideo: dummyVideoImg,
    },
    {
        id: 7,
        BatchID: "EE_SSC_486",
        BatchName: "Government Sector",
        TPName: "SCGJ",
        TCenter: "Richa Mehta",
        ToAssessmentDate: "0123456789",
        StartTime: "11:00 AM",
        EndTime: "02:00 PM",
        TotalCandidate: "1000",
        EnablePhoto: dummyImg,
        EnableVideo: dummyVideoImg,
    },
    {
        id: 8,
        BatchID: "EE_SSC_486",
        BatchName: "Government Sector",
        TPName: "SCGJ",
        TCenter: "Richa Mehta",
        ToAssessmentDate: "0123456789",
        StartTime: "11:00 AM",
        EndTime: "02:00 PM",
        TotalCandidate: "1000",
        EnablePhoto: dummyImg,
        EnableVideo: dummyVideoImg,
    },
    {
        id: 9,
        BatchID: "EE_SSC_486",
        BatchName: "Government Sector",
        TPName: "SCGJ",
        TCenter: "Richa Mehta",
        ToAssessmentDate: "0123456789",
        StartTime: "11:00 AM",
        EndTime: "02:00 PM",
        TotalCandidate: "1000",
        EnablePhoto: dummyImg,
        EnableVideo: dummyVideoImg,
    },
    {
        id: 10,
        BatchID: "EE_SSC_486",
        BatchName: "Government Sector",
        TPName: "SCGJ",
        TCenter: "Richa Mehta",
        ToAssessmentDate: "0123456789",
        StartTime: "11:00 AM",
        EndTime: "02:00 PM",
        TotalCandidate: "1000",
        EnablePhoto: dummyImg,
        EnableVideo: dummyVideoImg,
    },
    {
        id: 11,
        BatchID: "EE_SSC_486",
        BatchName: "Government Sector",
        TPName: "SCGJ",
        TCenter: "Richa Mehta",
        ToAssessmentDate: "0123456789",
        StartTime: "11:00 AM",
        EndTime: "02:00 PM",
        TotalCandidate: "1000",
        EnablePhoto: dummyImg,
        EnableVideo: dummyVideoImg,
    },
    {
        id: 12,
        BatchID: "EE_SSC_486",
        BatchName: "Government Sector",
        TPName: "SCGJ",
        TCenter: "Richa Mehta",
        ToAssessmentDate: "0123456789",
        StartTime: "11:00 AM",
        EndTime: "02:00 PM",
        TotalCandidate: "1000",
        EnablePhoto: dummyImg,
        EnableVideo: dummyVideoImg,
    }
]

export const SupportData = [
    {
        id: 1,
        TicketNo: "EE_SSC_486",
        AgencyName: "Government Sector",
        Category: "SCGJ",
        SubCategory: "Richa Mehta",
        Description: "0123456789",
        Image: dummyImg,
        TicketStatus: "02:00 PM",
        TicketPriority: "1000",
        AssignedTo: "SCGJ",
        CreatedDate: "SCGJ",
        UnreadMessage: "SCGJ",
    },
    {
        id: 2,
        TicketNo: "EE_SSC_486",
        AgencyName: "Government Sector",
        Category: "SCGJ",
        SubCategory: "Richa Mehta",
        Description: "0123456789",
        Image: dummyImg,
        TicketStatus: "02:00 PM",
        TicketPriority: "1000",
        AssignedTo: "SCGJ",
        CreatedDate: "SCGJ",
        UnreadMessage: "SCGJ",
    },
    {
        id: 3,
        TicketNo: "EE_SSC_486",
        AgencyName: "Government Sector",
        Category: "SCGJ",
        SubCategory: "Richa Mehta",
        Description: "0123456789",
        Image: dummyImg,
        TicketStatus: "02:00 PM",
        TicketPriority: "1000",
        AssignedTo: "SCGJ",
        CreatedDate: "SCGJ",
        UnreadMessage: "SCGJ",
    },
    {
        id: 4,
        TicketNo: "EE_SSC_486",
        AgencyName: "Government Sector",
        Category: "SCGJ",
        SubCategory: "Richa Mehta",
        Description: "0123456789",
        Image: dummyImg,
        TicketStatus: "02:00 PM",
        TicketPriority: "1000",
        AssignedTo: "SCGJ",
        CreatedDate: "SCGJ",
        UnreadMessage: "SCGJ",
    },
    {
        id: 5,
        TicketNo: "EE_SSC_486",
        AgencyName: "Government Sector",
        Category: "SCGJ",
        SubCategory: "Richa Mehta",
        Description: "0123456789",
        Image: dummyImg,
        TicketStatus: "02:00 PM",
        TicketPriority: "1000",
        AssignedTo: "SCGJ",
        CreatedDate: "SCGJ",
        UnreadMessage: "SCGJ",
    },
    {
        id: 6,
        TicketNo: "EE_SSC_486",
        AgencyName: "Government Sector",
        Category: "SCGJ",
        SubCategory: "Richa Mehta",
        Description: "0123456789",
        Image: dummyImg,
        TicketStatus: "02:00 PM",
        TicketPriority: "1000",
        AssignedTo: "SCGJ",
        CreatedDate: "SCGJ",
        UnreadMessage: "SCGJ",
    },
    {
        id: 7,
        TicketNo: "EE_SSC_486",
        AgencyName: "Government Sector",
        Category: "SCGJ",
        SubCategory: "Richa Mehta",
        Description: "0123456789",
        Image: dummyImg,
        TicketStatus: "02:00 PM",
        TicketPriority: "1000",
        AssignedTo: "SCGJ",
        CreatedDate: "SCGJ",
        UnreadMessage: "SCGJ",
    },
    {
        id: 8,
        TicketNo: "EE_SSC_486",
        AgencyName: "Government Sector",
        Category: "SCGJ",
        SubCategory: "Richa Mehta",
        Description: "0123456789",
        Image: dummyImg,
        TicketStatus: "02:00 PM",
        TicketPriority: "1000",
        AssignedTo: "SCGJ",
        CreatedDate: "SCGJ",
        UnreadMessage: "SCGJ",
    },
    {
        id: 9,
        TicketNo: "EE_SSC_486",
        AgencyName: "Government Sector",
        Category: "SCGJ",
        SubCategory: "Richa Mehta",
        Description: "0123456789",
        Image: dummyImg,
        TicketStatus: "02:00 PM",
        TicketPriority: "1000",
        AssignedTo: "SCGJ",
        CreatedDate: "SCGJ",
        UnreadMessage: "SCGJ",
    },
    {
        id: 10,
        TicketNo: "EE_SSC_486",
        AgencyName: "Government Sector",
        Category: "SCGJ",
        SubCategory: "Richa Mehta",
        Description: "0123456789",
        Image: dummyImg,
        TicketStatus: "02:00 PM",
        TicketPriority: "1000",
        AssignedTo: "SCGJ",
        CreatedDate: "SCGJ",
        UnreadMessage: "SCGJ",
    },
    {
        id: 11,
        TicketNo: "EE_SSC_486",
        AgencyName: "Government Sector",
        Category: "SCGJ",
        SubCategory: "Richa Mehta",
        Description: "0123456789",
        Image: dummyImg,
        TicketStatus: "02:00 PM",
        TicketPriority: "1000",
        AssignedTo: "SCGJ",
        CreatedDate: "SCGJ",
        UnreadMessage: "SCGJ",
    },
    {
        id: 12,
        TicketNo: "EE_SSC_486",
        AgencyName: "Government Sector",
        Category: "SCGJ",
        SubCategory: "Richa Mehta",
        Description: "0123456789",
        Image: dummyImg,
        TicketStatus: "02:00 PM",
        TicketPriority: "1000",
        AssignedTo: "SCGJ",
        CreatedDate: "SCGJ",
        UnreadMessage: "SCGJ",
    }
]